www:
  host: 0.0.0.0
  proxy: false
  secret: "zooMee6R"
  trustedUrlBase: http://mt:3010
  sandboxUrlBase: http://mt:3011

mysql:
  password: foovap1Etieb

redis:
  enabled: true

log:
  level: verbose
