'use strict';

import React, {Component} from 'react';
import PropTypes from 'prop-types';
import {withTranslation} from '../lib/i18n';
import {requiresAuthenticatedUser, Title, withPageHelpers} from '../lib/page';
import {Table} from '../lib/table';
import {HTTPMethod} from '../lib/axios';
import {withComponentMixins} from "../lib/decorator-helpers";
import {tableAddRestActionButton, tableRestActionDialogInit, tableRestActionDialogRender} from "../lib/modals";

@withComponentMixins([
    withTranslation,
    withPageHelpers,
    requiresAuthenticatedUser
])
export default class UserShares extends Component {
    constructor(props) {
        super(props);

        this.sharesTables = {};

        this.state = {};
        tableRestActionDialogInit(this);
    }

    static propTypes = {
        user: PropTypes.object
    }

    render() {
        const t = this.props.t;

        const renderSharesTable = (entityTypeId, title, typeName) => {
            const columns = [
                { data: 0, title: t('name') },
                { data: 1, title: t('role') },
                {
                    actions: data => {
                        const actions = [];
                        const autoGenerated = data[3];
                        const perms = data[4];

                        if (!autoGenerated && perms.includes('share')) {
                            const name = data[0];
                            const entityId = data[2];

                            tableAddRestActionButton(
                                actions,
                                this,
                                {
                                    method: HTTPMethod.PUT,
                                    url: 'rest/shares',
                                    data: {
                                        entityTypeId,
                                        entityId,
                                        userId: this.props.user.id
                                    },
                                    refreshTables: () => {
                                        for (const key in this.sharesTables) {
                                            this.sharesTables[key].refresh();
                                        }
                                    }
                                },
                                { icon: 'trash-alt', label: t('Unshare') },
                                t('Confirm Unsharing'),
                                t('Are you sure you want to remove the sharing of the {{typeName}} "{{name}}"?', {typeName, name}),
                                t('Removing sharing of the {{typeName}} "{{name}}"', {typeName, name}),
                                t('Sharing of the {{typeName}} "{{name}}" removed', {typeName, name}),
                                null
                            );
                        }

                        return actions;
                    }
                }
            ];

            return (
                <div>
                    <h3>{title}</h3>
                    <Table ref={node => this.sharesTables[entityTypeId] = node} withHeader dataUrl={`rest/shares-table-by-user/${entityTypeId}/${this.props.user.id}`} columns={columns} />
                </div>
            );
        };

        return (
            <div>
                {tableRestActionDialogRender(this)}
                <Title>{t('sharesForUserUsername', {username: this.props.user.username})}</Title>

                {renderSharesTable('namespace', t('namespaces'), t('namespace_lc'))}
                {renderSharesTable('list', t('lists'), t('list_lc'))}
                {renderSharesTable('template', t('Templates'), t('template_lc'))}
                {renderSharesTable('mosaicoTemplate', t('Mosaico Templates'), t('Mosaico template'))}
                {renderSharesTable('campaign', t('Campaigns'), t('campaign_lc'))}
                {renderSharesTable('customForm', t('customForms-1', t('custom forms')))}
                {renderSharesTable('report', t('reports'), t('report_lc'))}
                {renderSharesTable('reportTemplate', t('reportTemplates'), t('report template'))}
                {renderSharesTable('sendConfiguration', t('Send Configurations'), t('send configuration'))}
            </div>
        );
    }
}
