kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
stringData:
  production.yaml: |-
    title: mailtrain

    gdpr:
      deleteDataAfterUnsubscribe:
        enabled: false
        secondsAfterUnsubscribe: 86400 # 1 day
      deleteSubscriptionAfterUnsubscribe:
        enabled: false
        secondsAfterUnsubscribe: 2592000 # 30 days
    editors:
    - mosaico
    - mosaicoWithFsTemplate
    - grapesjs
    - ckeditor4
    - codeeditor

    defaultLanguage: en-US

    enabledLanguages:
    - en-US

    redis:
      enabled: {{ .Values.redis.enable }}
      host: {{ .Values.redis.host }}
      port: 6379
      db: 5
    log:
      level: info
      sendStacktracesToClient: false
    www:
      trustedPort: 3000
      sandboxPort: 3003
      publicPort: 3004
      host: 0.0.0.0
      trustedUrlBase: http://localhost:3000
      # URL base for sandbox urls (logged-in users). It must be absolute (starting with http:// or https://) and contain the sandbox port.
      sandboxUrlBase: http://localhost:3003
      # URL base for public urls (campaign recipients). It must be absolute (starting with http:// or https://) and contain the sandbox port.
      publicUrlBase: http://localhost:3004


      # Secret for signing the session ID cookie
      secret: {{ randAlphaNum | quote }}
      # Session length in seconds when remember me is checked
      remember: 2592000 # 30 days
      # logger interface for expressjs morgan
      log: dev
      # Is the server behind a proxy? true/false
      # Set this to true if you are serving Mailtrain as a virtual domain through Nginx or Apache
      proxy: true
      # maximum POST body size
      postSize: 20MB

    mysql:
      host: {{ .Values.database.hostname }}
      user: {{ .Values.database.username }}
      password: {{ .Values.database.password }}
      database: {{ .Values.database.database }}
      port: 3306
      charset: utf8mb4
      timezone: local

    verp:
      enabled: false
      port: 25
      host: 0.0.0.0

    ldap:
      # enable to use ldap user backend
      enabled: false
      # method is ldapjs or ldapauth - it chooses the library to be used. If not given, it chooses the one present.
      # method: ldapjs
      host: localhost
      port: 3002
      baseDN: ou=users,dc=company
      filter: (|(username={{username}})(mail={{username}}))
      # Username field in LDAP (uid/cn/username)
      uidTag: username
      # nameTag identifies the attribute to be used for user's full name
      nameTag: username
      passwordresetlink:
      newUserRole: master
      # Global namespace id
      newUserNamespaceId: 1
      # Use a different user to bind LDAP (final bind DN will be: {{uidTag}}: {{bindUser}},{{baseDN}})
      bindUser: name@company.net
      bindPassword: mySecretPassword

    postfixBounce:
      # Enable to allow writing Postfix bounce log to Mailtrain listener
      # If enabled, tail mail.log to Mailtrain with the following command:
      #     tail -f -n +0 /var/log/mail.log | nc localhost 5699 -
      enabled: false
      port: 5699
      # allow connections from localhost only
      host: 127.0.0.1

    # extra options for nodemailer
    nodemailer:
      #textEncoding: base64

    queue:
      # How many parallel sender processes to spawn
      processes: 4

    cors:
      # Allow subscription widgets to be embedded
      # origins: ['https://www.example.com']

    mosaico:
      # Installed templates
      fsTemplates:
      - key: versafix-1
        label: Versafix One
      # Inject custom scripts
      # customscripts:
      # - /mosaico/custom/my-mosaico-plugin.js
      fileCache:
        blockThumbnails:
          maxSize: 100 # megabytes
          pruneInterval: 60 # seconds
        images:
          maxSize: 1024 # megabytes
          pruneInterval: 60 # seconds


    grapesjs:
    # Installed templates
      templates:
        - key: demo
          label: HTML Template
        - key: aves
          label: MJML Template

    reports:
      # The whole reporting functionality can be disabled below if the they are not needed and the DB cannot be
      # properly protected.
      # Reports rely on custom user defined Javascript snippets defined in the report template. The snippets are run on the
      # server when generating a report. As these snippets are stored in the DB, they pose a security risk because they can
      # help gaining access to the server if the DB cannot
      # be properly protected (e.g. if it is shared with another application with security weaknesses).
      # Mailtrain mitigates this problem by running the custom Javascript snippets in a chrooted environment and under a
      # DB user that cannot modify the database (see userRO in [mysql] above). However the chrooted environment is available
      # only if Mailtrain is started as root. The chrooted environment still does not prevent the custom JS script in
      # performing network operations and in generating XSS attacks as part of the report.
      # The bottom line is that if people who are creating report templates or have write access to the DB cannot be trusted,
      # then it's safer to switch off the reporting functionality below.
      enabled: true

    testServer:
      # Starts a vanity server that redirects all mail to /dev/null
      # Mostly needed for local development
      enabled: false
      port: 5587
      mailboxServerPort: 3001
      host: 0.0.0.0
      username: testuser
      password: testpass
      logger: false

    builtinZoneMTA:
      enabled: true
      host: localhost
      port: 2525
      mongo: mongodb://127.0.0.1:27017/zone-mta
      redis: redis://localhost:6379/2
      log:
        level: warn
      processes: 2
      connections: 5

    seleniumWebDriver:
      browser: phantomjs


    roles:
      global:
        master:
          name: Global Master
          admin: true
          description: All permissions
          permissions: [rebuildPermissions, createJavascriptWithROAccess, displayManageUsers, manageBlacklist, manageSettings, setupAutomation]
          rootNamespaceRole: master
        campaignsAdmin:
          name: Campaigns Admin
          description: Under the namespace in which the user is located, the user has all permissions for managing lists, templates and campaigns and the permission to send to send configurations.
          permissions: [setupAutomation]
          ownNamespaceRole: campaignsAdmin
        nobody:
          name: None
          description: No permissions
          permissions: []

      namespace:
        master:
          name: Master
          description: All permissions
          permissions: [view, edit, delete, share, createNamespace, createList, createCustomForm, createReport, createReportTemplate, createTemplate, createMosaicoTemplate, createSendConfiguration, createCampaign, manageUsers]
          children:
            sendConfiguration: [viewPublic, viewPrivate, edit, delete, share, sendWithoutOverrides, sendWithAllowedOverrides, sendWithAnyOverrides]
            list: [view, edit, delete, share, viewFields, manageFields, viewSubscriptions, manageSubscriptions, viewSegments, manageSegments, viewImports, manageImports]
            customForm: [view, edit, delete, share]
            campaign: [view, edit, delete, share, viewFiles, manageFiles, viewAttachments, manageAttachments, viewTriggers, manageTriggers, send, viewStats, fetchRss]
            template: [view, edit, delete, share, viewFiles, manageFiles]
            report: [view, edit, delete, share, execute, viewContent, viewOutput]
            reportTemplate: [view, edit, delete, share, execute]
            mosaicoTemplate: [view, edit, delete, share, viewFiles, manageFiles]
            namespace: [view, edit, delete, share, createNamespace, createList, createCustomForm, createReport, createReportTemplate, createTemplate, createMosaicoTemplate, createSendConfiguration, createCampaign, manageUsers]

        campaignsAdmin:
          name: Campaigns Admin
          description: In the respective namespace, the user has all permissions for managing lists, templates and campaigns and the permission to send to send configurations.
          permissions: [view, edit, delete, share, createNamespace, createList, createCustomForm, createReport, createTemplate, createMosaicoTemplate, createCampaign]
          children:
            sendConfiguration: [viewPublic, sendWithoutOverrides, sendWithAllowedOverrides]
            list: [view, edit, delete, share, viewFields, manageFields, viewSubscriptions, manageSubscriptions, viewSegments, manageSegments, viewImports, manageImports]
            customForm: [view, edit, delete, share]
            campaign: [view, edit, delete, share, viewFiles, manageFiles, viewAttachments, manageAttachments, viewTriggers, manageTriggers, send, viewStats, fetchRss]
            template: [view, edit, delete, share, viewFiles, manageFiles]
            report: [view, edit, delete, share, execute, viewContent, viewOutput]
            reportTemplate: [view, share, execute]
            mosaicoTemplate: [view, edit, delete, share, viewFiles, manageFiles]
            namespace: [view, edit, delete, share, createNamespace, createList, createCustomForm, createReport, createTemplate, createMosaicoTemplate, createCampaign]

        campaignsCreator:
          name: Campaigns Creator
          description: In the respective namespace, the user has all permissions for templates and campaigns.
          permissions: [view, createTemplate, createCampaign]
          children:
            sendConfiguration: [viewPublic]
            campaign: [view, edit, delete, share, viewFiles, manageFiles, viewAttachments, manageAttachments, viewTriggers, manageTriggers, fetchRss]
            template: [view, edit, delete, share, viewFiles, manageFiles]

      sendConfiguration:
        master:
          name: Master
          description: All permissions
          permissions: [viewPublic, viewPrivate, edit, delete, share, sendWithoutOverrides, sendWithAllowedOverrides, sendWithAnyOverrides]
        campaignsCreator:
          name: Campaigns Creator
          description: The user can only use the send configuration in setting up a campaign. However, this gives no permission to send.
          permissions: [viewPublic]

      list:
        master:
          name: Master
          description: All permissions
          permissions: [view, edit, delete, share, viewFields, manageFields, viewSubscriptions, manageSubscriptions, viewSegments, manageSegments, viewImports, manageImports]
        campaignsCreator:
          name: Campaigns Creator
          description: The user can only use the list in setting up a campaign. However, this gives no permission to view subscriptions or to send to the list.
          permissions: [view, viewFields, viewSegments]

      customForm:
        master:
          name: Master
          description: All permissions
          permissions: [view, edit, delete, share]

      campaign:
        master:
          name: Master
          description: All permissions
          permissions: [view, edit, delete, share, viewFiles, manageFiles, viewAttachments, manageAttachments, viewTriggers, manageTriggers, send, viewStats, manageMessages, fetchRss]
        campaignsCreator:
          name: Campaigns Creator
          description: The user can setup the campaign but cannot send it.
          permissions: [view, edit, delete, share, viewFiles, manageFiles, viewAttachments, manageAttachments, viewTriggers, manageTriggers, fetchRss]
        rssTrigger:
          name: RSS Campaign Trigger
          description: Allows triggering a fetch of an RSS campaign
          permissions: [fetchRss]

      template:
        master:
          name: Master
          description: All permissions
          permissions: [view, edit, delete, share, viewFiles, manageFiles]

      report:
        master:
          name: Master
          description: All permissions
          permissions: [view, edit, delete, share, execute, viewContent, viewOutput]

      reportTemplate:
        master:
          name: Master
          description: All permissions
          permissions: [view, edit, delete, share, execute]

      mosaicoTemplate:
        master:
          name: Master
          description: All permissions
          permissions: [view, edit, delete, share, viewFiles, manageFiles]
